---
title: "Homework 05: Factor and figure management; Repo hygiene"
author: "RH"
date: "October 20, 2017"
output:  
  github_document: 
    toc: true
    toc_depth: 5
---


```{r setup, include=FALSE}
## Loading libraries
library(tidyverse)
library(gapminder)
library(knitr)
library(forcats)

```


### Factor management

##### Drop Oceania
```{r}
gapminder %>%
  filter(continent == "Oceania")        # we have 24 observations in Oceania for 2 countries

dropOceania <- gapminder %>% 
  filter(continent != "Oceania") %>%    # create a new variable dropOceania which filters out Oceania
  droplevels()

dropOceania %>%
  group_by(continent) %>%
  summarize(mean_pop = mean(pop))       # we see here that oceania is no longer listed
```


##### Reorder the levels of country 

```{r}
gapReorder <- fct_reorder(dropOceania$country, 
                          dropOceania$lifeExp, 
                          fun = max, 
                          .desc= TRUE) %>%      # we are reordering country based on lifeExp 
              levels() %>%
              head(8)                         

# Let's look at this new reordered data
gapReorder

```

```{r}
maxlife <- dropOceania %>% 
  filter(country %in% gapReorder)

  # now we can plot this new data
  ggplot(maxlife, aes(x=year, y=lifeExp, colour = country)) +
  geom_line(size = 1) + 
  facet_wrap(~country, nrow = 2) +
  scale_x_continuous(breaks = c(1952, 1962, 1972, 1982, 1992, 2002),
                   labels = c("50", "60", "70", "80", "90", "00"))


```



Using arrange to draw a figure gives the following:

```{r}
arrange(maxlife, lifeExp) %>% 
  ggplot(aes(x=year, y=lifeExp, colour = country)) +
  geom_line() +
  facet_wrap(~country) + 
  theme_bw()
```

The look of this graph is quite similar to the previous one.


### File I/O

Let's use write_csv and read_csv to get this subset of data in and out of r

```{r}
write_csv(maxlife, "~/maxlife.csv")         # writes the file
MaxGDP_Read <- read_csv("~/maxlife.csv")    # reads back the file
```




### Visualization design

Objective: Remake at least one figure 


Let's try and make a plot I made in hw04 look better

```{r}
dropOceania %>%
  select (country, continent, gdpPercap, pop, year) %>%
  ggplot(aes(x = gdpPercap, y = pop, colour = continent)) + 
  geom_point(size = 4, alpha = .5) + 
  scale_x_continuous(breaks = c(10000, 20000, 30000, 40000, 50000), labels = c("10k", "20k", "30k", "40k", "50k")) + 
  geom_hline(yintercept = 5, colour = "grey", alpha = .7)+
  theme_minimal() +
  scale_colour_brewer(palette="Spectral")
```














